name: whats_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1




environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #flutter_native_splash:
  flutter_native_splash: ^2.4.6

  #getX package :
  get: ^4.6.6

  #intl
  intl: ^0.20.2

  #intl_phone_field
  intl_phone_field: ^3.2.0

  #iconsax
  iconsax: ^0.0.8

  #pinput
  pinput: ^4.0.0

  #lottie
  lottie: ^3.1.3

  #cached_network_image
  cached_network_image: ^3.4.1







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
    - assets/fonts/
    - assets/animation/community/


  fonts:
    - family: "Nunito"
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300

        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800

        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic

        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500

        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400

        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic